# Generated by Django 4.1.7 on 2023-03-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='Юзеры')),
                ('user', models.TextField(verbose_name='Инфо')),
            ],
        ),
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
